package com.hikvision.modules.resteasy.rs;

import org.springframework.stereotype.Service;

import com.hikvision.api.v1.ApiService;

/**
 * ApiServiceImpl
 * generated by hik-ga-archetype-api
 * 
 * @author 
 */
@Service
public class ApiServiceImpl implements ApiService {
  
  // ApiService implements here...
  
}